app/urls.py
from django.urls import path
from . import views
app_name = 'app'


urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('profiles/', views.ProfileList.as_view(), name='profiles-list'),
    path('profile-create/', views.ProfileCreate.as_view(), name='profile-create'),
    path('movie/<str:profile_id>/', views.MovieList.as_view(), name='movie-list'),
    path('movie/detail/<str:movie_id>/', views.MovieDetail.as_view(), name='movie-detail'),
    path('movie/play/<str:movie_id>/', views.PlayMovie.as_view(), name='play-movie'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

AGE_LIMIT = (
    ('All', 'All'),
    ('Kids', 'Kids'),
)

MOVIE_TYPE = (
    ('Seasonal', 'Seasonal'),
    ('Single', 'Single'),
)

class CustomUser(AbstractUser):
    profiles = models.ManyToManyField('Profile', blank=True)


class Profile(models.Model):
    name = models.CharField(max_length=300)
    age_limit = models.CharField(choices=AGE_LIMIT, max_length=10)
    uuid = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=1000)
    desc = models.TextField(blank=True, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    uuid = models.UUIDField(default=uuid.uuid4)
    type = models.CharField(choices=MOVIE_TYPE, max_length=10)
    video = models.ManyToManyField('Video')
    image = models.ImageField(upload_to='covers/')
    age_limit = models.CharField(choices=AGE_LIMIT, max_length=10)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=1000)
    file = models.FileField(upload_to='movies/')    

    def __str__(self):
        return self.title

app/forms.py
from django import forms
from .models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['uuid',]

app/views.py
from multiprocessing import context
import uuid
from django.shortcuts import redirect, render
from django.views import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import ProfileForm
from .models import Profile, Movie

class Index(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('app:profiles-list')
        return render(request, 'index.html')


method_decorator(login_required, name='dispatch')
class ProfileList(View):
    def get(self, request, *args, **kwargs):
        profiles = request.user.profiles.all()

        context = {
            'profiles': profiles
        }

        return render(request, 'profileList.html', context)

method_decorator(login_required, name='dispatch')
class ProfileCreate(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'profileCreate.html')
    
    def post(self, request, *args, **kwargs):
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = Profile.objects.create(**form.cleaned_data)
            if profile:
                request.user.profiles.add(profile)
                return redirect('app:profiles-list')
        context = {
            'form': form
        }
        return render(request, 'profileCreate.html', context)


method_decorator(login_required, name='dispatch')
class MovieList(View):
    def get(self, request, profile_id, *args, **kwargs):
        try:
            profile = Profile.objects.get(uuid=profile_id)
            movies = Movie.objects.filter(age_limit=profile.age_limit)
            last_movie = Movie.objects.filter(age_limit=profile.age_limit).order_by('-id')
            if profile not in request.user.profiles.all():
                return redirect('app:profiles-list')
            
            context = {
                'movies': movies,
                'last_movie': last_movie,
            }
            return render(request, 'movieList.html', context)
        except Profile.DoesNotExist:
            return redirect('app:profiles-list')


method_decorator(login_required, name='dispatch')
class MovieDetail(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            context = {
                'movie': movie,
            }

            return render(request, 'movieDetail.html', context)
        except Movie.DoesNotExist:
            return redirect('app:movies-list')

method_decorator(login_required, name='dispatch')
class PlayMovie(View):
    def get(self, request, movie_id, *args, **kwargs):
        try:
            movie = Movie.objects.get(uuid=movie_id)
            video = movie.video.values()
            context = {
                'video': list(video),
            }

            return render(request, 'showMovie.html', context)
        except Movie.DoesNotExist:
            return redirect('app:movies-list')

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body class="bg-black text-gray-100">
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </a>
            {% endif %}
        </div>
    </nav>
    <header class="min-h-screen bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'assets/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Unlimited movies, TV shows, and more.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Watch anywhere. Cancel anytime.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Ready to watch? Enter your email to create or restart your membership.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <input type="email" name="" id="" placeholder="Email address" class="md:py-5 py-4 px-2 placeholder-gray-500 rounded-tl-sm rounded-bl-sm outline-none  text-gray-900 bg-gray-50 block w-8/12 md:w-3/4">
                    <a href="{% url "account_signup" %}" class="bg-primary_red font-medium md:font-normal md:w-1/4 flex justify-center items-center py-4 px-1 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl">
                        <span>
                            Get Started
                        </span>
                        <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                    </a>
                </div>
            </div>
        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'assets/tv.png' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center order-2'>
            <img src="{% static 'assets/mobile-0819.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>
        
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'assets/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">
            
            <li>&copy; All Right Reserved | 2022</li>
            <li> Netflix Clone</li>
            <li>By: Uchqun Usmonov</li>
        </ul>
    </footer>
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Login</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </button>
        </div>
    </nav>
    <header class="min-h-screen w-full bg-black bg-opacity-75 showcase border-gray-600 border-b-8 flex justify-center py-20 bg-no-repeat"  style="background-image: url('{% static 'assets/background_netflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 w-6/12  flex items-center flex-col">
            <form class="bg-black bg-opacity-70 py-8 px-4 w-8/12 rounded-md" >
                <h1 class="text-4xl font-semibold text-center ">
                    Log In
                </h1>
                <div class=" text-center my-4">
                    <p class="text-primary_red ">
                        Wrong credentials
                    </p>
                   
                </div>
                <div> 
                    <Label class='text-lg font-medium mb-3'>
                        Email
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="email" name="email" id="id_email" placeholder="Your Email">
                </div>
                <div class='my-3'> 
                    <Label class='text-lg font-medium mb-3'>
                        Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password" id="id_password" placeholder="Password">
                </div>
                <div class="flex justify-center items-center">
                    <button class="py-2 px-4 bg-primary_red text-gray-100 font-medium text-lg rounded-md">
                        Log In
                    </button>
                </div>

                <div class="text-center my-4">
                    <p>
                        Do not have account <a href="signup.html" class="text-blue-600"> Sign Up</a>
                    </p>
                </div>
            </form>
        </div>
    </header>
</body>
</html>

templates/movieDetail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix - Detail Page</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body class='font-primary'>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </a>
            {% endif %}
        </div>
        
    </nav>
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('{{movie.image.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4" style="font-weight: bolder;">
                    {{movie.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{movie.desc | slice:':300'}}
                </p>
                <div class="flex my-4">

                    <a href="{% url 'app:play-movie' movie_id=movie.uuid %}" class="flex items-center bg-white py-2 px-5 rounded-md">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </a>
    
                    
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                    Description
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                        {{movie.desc}}
                    </p>
                </div>
            </div>
        </section>
        
    </main>
    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            
            if(scrollY>200){
                nav.classList.add('bg-gray-900')
          
            }else{
                nav.classList.remove('bg-gray-900')
                
            }
        })

    </script>
</body>
</html>

templates/movieList.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix - Profile</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body class='font-primary'>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </a>
            {% endif %}
        </div>
        
    </nav>
    <main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex justify-end items-end bg-cover" style="background-image: url('{{last_movie.0.image.url}}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{last_movie.0.title}}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{last_movie.0.desc|slice:'290'}}
                </p>
                <div class="flex my-4">

                    <a href="{% url 'app:play-movie' movie_id=last_movie.0.uuid %}" class="flex items-center bg-white py-2 px-5 rounded-md">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </a>
    
                    <a href="{% url 'app:movie-detail' movie_id=last_movie.0.uuid %}" class="ml-4 text-white flex items-center bg-gray-500 bg-opacity-80 py-2 px-5 rounded-md">
                       
                        <ion-icon name="information-circle-outline" class="text-2xl" ></ion-icon>
                        <span class="ml-3 font-medium">
                            More Info
                        </span>
                    </a>
                </div>
            </div>
        </section> 
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Popular on Netflix
                </h2>
                <div class="flex justify-center  items-center min-w-full  movie_lis">
                    {% for movie in movies %}
                        <a href="{% url 'app:movie-detail' movie_id=movie.uuid %}">
                            <div class=" h-40 m-4  bg-blue-500 flex-shrink-0 rounded-md cursor-pointer w-40">
                                <img src="{{movie.image.url}}" class="w-full h-full " alt="">
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        </section>
        
    </main>
</body>
</html>

templates/profileCreate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix - Profile</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>
        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </a>
            {% endif %}
        </div>

        
    </nav>
    <section class='bg-primary_black min-h-screen py-20 md:py-32 flex-col flex items-center' style="background-image: url('{% static 'assets/background_netflix.jpg' %}');">
        <div class="flex flex-wrap justify-center  w-10/12  md:w-6/12">
            <form class="w-full md:w-8/12 bg-gray-900 p-5 rounded-lg" method="POST">{% csrf_token %}
                <h1 class="text-4xl text-center text-gray-100 font-medium">
                    Create A Profile
                </h1>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Profile Name
                    </Label>
                    <input required class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full" type="text" name="name" placeholder="Profile name">
                </div>
                <div class="my-4"> 
                    <Label class='text-lg text-gray-200 font-medium mb-3'>
                        Maturity Level
                    </Label>
                    <select class="p-2 bg-gray-500 rounded-sm text-gray-200 outline-none block w-full"  name="age_limit" >
                        <option value="All">All</option>
                        <option value="Kids">Kids</option>
                    </select>
                </div>
                <div class="flex justify-center items-center">
                    <button class="px-4 py-2 rounded-md outline-none bg-primary_red text-gray-100" type="submit">Create Profile</button>
                </div>
            </form> 
        </div>
        
    </section>
</body>
</html>

templates/profileList.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix - Profile</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>
        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </a>
            {% endif %}
        </div>

        
    </nav>
    <section class='bg-primary_black min-h-screen py-20 md:py-0 flex-col flex justify-center items-center' style="background-image: url('{% static 'assets/background_netflix.jpg' %}');">
        <h2 class="text-center font-medium text-5xl my-4 text-gray-100">
            Who's watching ?
        </h2>

        <div class="flex flex-wrap justify-center items-center w-10/12  md:w-6/12">
            {% for profile in profiles %}
                <a href="{% url 'app:movie-list' profile_id=profile.uuid %}">
                    <div class="w-32 h-32 m-4  bg-blue-500 rounded-md cursor-pointer">
                        <p class="text-6x1" style="font-weight:900; ">{{ profile.name | slice:':1' }}</p>
                        <p>{{ profile.name }}</p>
                    </div>
                </a>
            {% endfor %}
        </div>
        <div class="flex justify-center items-center">
            <a href="{% url 'app:profile-create' %}" class="px-4 py-2 rounded-md outline-none bg-gray-400 text-gray-100">
                Add A New Profile
            </a>
        </div>
    </section>
</body>
</html>

templates/showMovie.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix - Movie</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
    <style>
        .player::-webkit-progress-bar{
            color: red;
        }
    </style>
</head>
<body class='font-primary'>
    <nav class="flex justify-between items-center py-3 bg-gray-900  px-4 w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>
        <div>
            {% if request.user.is_authenticated %}
                <a href="{% url 'account_logout' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Logout
                </a>
            {% else %}
                <a href="{% url 'account_login' %}" class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                    Sign In 
                </a>
            {% endif %}
        </div>
    </nav>
    <main class='bg-primary_black h-full w-full '>
        {{movie|json_script:"movie_data"}}
        <video src="{% static 'assets/test.mp4' %}" controls class="w-full h-screen player"></video>
        
    </main>
    <script>
        const videoEL = document.querySelector('video');
        const movie_data = JSON.parse(document.getElementById('movie_data').textContent);
        const url = new URL(location.href);
        const video_param = parseInt(url.searchParams.get('epi'))?parseInt(url.searchParams.get('epi')):0;
        videoEL.setAttribute('src', `http://localhost:8000/media/${movie_data[video_param].file}`)
    </script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Netflix Sign Up</title>
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@5.4.0/dist/ionicons/ionicons.esm.js"></script>
</head>
<body>
    <nav class="flex justify-between items-center py-3 px-4 fixed w-full z-50">
        <div class="w-6/12">
            <img src="{% static 'assets/netflix.png' %}" alt="logo" class="w-5/12 md:w-2/12">
        </div>

        <div>
            <button class='bg-primary_red py-1 px-3 text-white md:text-lg rounded-md'>
                Sign In 
            </button>
        </div>
    </nav>
    <header class="min-h-screen w-full bg-black bg-opacity-75 showcase relative border-gray-600 border-b-8 flex justify-center py-20 bg-no-repeat"  style="background-image: url('{% static 'assets/background_netflix.jpg' %}');">
        <div class="z-10 min-h-full py-32 md:py-0 text-gray-100 w-6/12  flex items-center flex-col">
            <form class="bg-black bg-opacity-70 min-h-full py-8 px-4 w-8/12 rounded-md" >
                <h1 class="text-4xl font-semibold text-center ">
                    Sign Up
                </h1>
                <div class=" text-center my-4">
                    <p class="text-primary_red ">
                        Email is not valid
                    </p>
                    <p class="text-primary_red ">
                        Password does not match
                    </p>
                </div>
                <div> 
                    <Label class='text-lg font-medium mb-3'>
                        Email
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="email" name="email" id="id_email" placeholder="Your Email">
                </div>
                <div class='my-3'> 
                    <Label class='text-lg font-medium mb-3'>
                        Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password" id="id_password" placeholder="Password">
                </div>
                <div class='my-3'> 
                    <Label class='text-lg font-medium mb-3'>
                        Confirm Password
                    </Label>
                    <input class="p-2 bg-gray-200 rounded-sm text-gray-900 outline-none block w-full" type="password" name="password2" id="id_password2" placeholder="Password">
                </div>
                <div class="flex justify-center items-center">
                    <button class="py-2 px-4 bg-primary_red text-gray-100 font-medium text-lg rounded-md">
                        Sign Up
                    </button>
                </div>

                <div class="text-center mt-4">
                    <p>
                        Have account already ? <a href="login.html" class="text-blue-600"> Log In</a>
                    </p>
                </div>
            </form>
        </div>
    </header>
</body>
</html>